CREATE TABLE employesss (
    id_emp NUMBER PRIMARY KEY,
    nom_emp VARCHAR2(50),
    poste VARCHAR2(30),
    salaire NUMBER(10, 2),
    date_embauche DATE
);


create department (
    id_departement NUMBER PRIMARY KEY,
    nom_departement VARCHAR2(50)
);


-- CREATE TABLE log_modification (
--     id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     id_emp NUMBER,
--     action_type VARCHAR2(10),
--     date_action DATE,
--     user_action VARCHAR2(30)
-- );



CREATE TABLE log_modification (
    id_log NUMBER PRIMARY KEY,
    id_emp NUMBER,
    action_type VARCHAR2(10),
    date_action DATE,
    user_action VARCHAR2(30)
);


CREATE OR REPLACE TRIGGER trg_log_modification_id
BEFORE INSERT ON log_modification
FOR EACH ROW
BEGIN
    IF :NEW.id_log IS NULL THEN
        SELECT seq_log_id.NEXTVAL INTO :NEW.id_log FROM dual;
    END IF;
END;
/

